### ISSUE TITLE
Data documentation mismatches

### ISSUE THREAD

**Issue by jrnold** [kosukeimai/qss-package#10]
When running `R CMD check`, I get the following `WARNING` messages

```
checking for code/documentation mismatches ... WARNING
Data codoc mismatches from documentation object 'World':
Variables in data frame 'World'
  Code: age births country deaths period py.men py.women
  Docs: age births country deaths l_x period py.men py.women

Data codoc mismatches from documentation object 'intrade12':
Variables in data frame 'intrade12'
  Code: .row PriceD PriceR VolumeD VolumeR day state statename
  Docs: .row MarketD MarketR PriceD PriceR VolumeD VolumeR day state
        statename
```

**Comment by kosukeimai** [comment]
@tylersimko can you fix these?

**Comment by tylersimko** [comment]
@kosukeimai @jrnold Okay. Just to make sure I understand what these are saying - It looks like there are extra variables mentioned in the docs for some reason. Will the warning go away if I remove, for example,`l_x` from the documentation mentioned in the first one?

**Comment by jrnold** [comment]
Yes, that's what the error message is saying. You may want to check that it isn't a deeper issue. Since there are data sets with the same names but different folders in `qss` it is possible that they have different variable names. I think I caught this in `data-raw/build.R`, but you should check.

**Comment by kosukeimai** [comment]
@tylersimko can you finish up this fix?

**Comment by tylersimko** [comment]
@kosukeimai I just put it up [here](https://github.com/kosukeimai/qss-package/pull/16/commits/4bbc504335b8d42f4c2b981e2c286aebfab91f4c), I think this will do it.
