### ISSUE TITLE
Pkgdown website

### ISSUE THREAD

**Issue by jrnold** [kosukeimai/qss-package#12]
Currently there is [pkgdown](https://hadley.github.io/pkgdown/) documentation in `docs/`. This is a website built directly from the R doc pages and vignettes. However, right now the repo is not configured to serve the documentation. GitHub can directly serve web-pages from a repo; instructions are [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/). If configured, `https://kosukeimai.github.io/qss-package` would point to the docs for this package (potentially including the R scripts for each chapter as vignettes).  If you aren't going to use it, we should delete the `docs` directory.

**Comment by kosukeimai** [comment]
I'm still talking to PU Press to figure this out.  I hope to resolve this issue soon.

**Comment by jrnold** [comment]
No problem. This issue was largely to make you aware of one of the new R tools available. I'm guessing the the press may be concerned about having multiple websites. Though pkgdown can be used to build a more comprehensive website, at the moment all it's doing is making HTML pages from the vignettes and documentation; since it's unlikely that this R package will go on CRAN (due to the size of the data) this would provide another way to browse documentation over the web.

**Comment by kosukeimai** [comment]
PU Press agreed that we should use pkgdown to create a website for the package.  They will decide whether to link it from the book site or simply include it in the site (in either case, it will remain open).  Is there anything we need to do for this?

**Comment by jrnold** [comment]
Right now, almost nothing.

1.  Follow the instructions in the first post to setup the repo to serve the directory `docs` as a webpage at https://kosukeimai.github.io/qss-package. 
2. Install [pkgdown](https://hadley.github.io/pkgdown/): `devtools::install_github("hadley/pkgdown")`.
3. Run the following locally
    ```
    pkgdown::build_site()
    ```
4. Push to the repo.
5. See the new webpage

There's instructions on pkgdown to customize the configuration. But the defaults seem pretty good.

**Comment by kosukeimai** [comment]
Thanks.  The website has been built.
