### ISSUE TITLE
demo files

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/qss-package#3]
@tylersimko Can you make sure that the demo files run without error?  In particular, the data sets need to be loaded via the `data()` function rather than the `read.csv()` function.  There may be other issues too.  Thanks.

**Comment by jrnold** [comment]
Maybe it is better to make these into vignettes? With a few minor changes to formatting (e.g. http://rmarkdown.rstudio.com/articles_report_from_r_script.html) we can turn the R scripts to R markdown via `knitr::spin()` and then they'll appear as nicely formatted vignettes.

**Comment by tylersimko** [comment]
@kosukeimai Okay, I've just made a new branch called `fixDemoFiles.` I'll open a PR soon.
